# Generated by Django 5.0.4 on 2024-05-13 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_book_add_date_alter_book_book_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 13, 11, 40, 25, 774192, tzinfo=datetime.timezone.utc)),
        ),
    ]
